import React from "react";
import AppNav from "@/components/AppNav";

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-[#000000] text-[#B3B3B3] flex flex-col">
      <AppNav />
      <main className="flex-1 max-w-4xl w-full mx-auto px-6 py-20">
        <h1 className="text-3xl font-bold text-white mb-8">Risk Disclaimer</h1>
        
        <div className="p-6 bg-[#FF3B5C]/10 border border-[#FF3B5C]/20 rounded-2xl mb-8">
          <h2 className="text-[#FF3B5C] font-bold text-lg mb-2">NOT FINANCIAL ADVICE</h2>
          <p className="text-sm leading-relaxed text-[#FF3B5C]/80">
            Nothing on this platform constitutes financial advice. Cryptocurrency markets, and memecoins in particular, are highly speculative and volatile. 
            Do Your Own Research (DYOR) before interacting with any digital assets.
          </p>
        </div>

        <div className="space-y-6 text-sm leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Devnet Operations</h2>
            <p>
              PumpDraft currently operates on the Solana <strong>Devnet</strong>. The "SOL" utilized within this platform is testnet currency. 
              It has zero real-world value and cannot be redeemed, traded, or sold for fiat currency or Mainnet crypto assets. 
              Do not send real SOL to any addresses generated by or associated with this application.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">Experimental Technology</h2>
            <p>
              This platform utilizes experimental smart contract technology. While we strive to ensure the security and accuracy of our pari-mutuel payout systems, 
              bugs, exploits, or network congestion on the Solana blockchain may result in delayed, failed, or inaccurate transactions. 
              We are not liable for any such failures.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">No Liability</h2>
            <p>
              By using PumpDraft, you acknowledge and agree that the creators, developers, and operators of this platform shall not be held liable for any damages, 
              losses of funds, emotional distress, or other negative consequences resulting from your use of the platform. You interact with the smart contracts entirely at your own risk.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
